### ISSUE TITLE
Not loading on Wikibase 1.37.6

### ISSUE THREAD

**Issue by despens** [ProfessionalWiki/WikibaseLocalMedia#19]
### Setup

- Wikibase Local Media version: latest (installed using composer, ` professional-wiki/wikibase-local-media:*`)
- Wikibase version: 1.37 (97d07b1)
- MediaWiki version: 1.37.6
- PHP version: 8.0.23

### Issue

When extension is loaded, it is trying to call `Wikibase\Repo\WikibaseRepo::getDefaultInstance()` which apparently is not supported anymore.

```
[bf9f832a57800df03450b5c5] /wiki/Special:SpecialPages Error: Call to undefined method Wikibase\Repo\WikibaseRepo::getDefaultInstance()

Backtrace:

from /var/www/html/extensions/WikibaseLocalMedia/src/WikibaseLocalMedia.php(42)
#0 /var/www/html/extensions/WikibaseLocalMedia/src/HookHandlers.php(23): Wikibase\LocalMedia\WikibaseLocalMedia->getFormatterBuilder()
#1 [internal function]: Wikibase\LocalMedia\HookHandlers::Wikibase\LocalMedia\{closure}(string, ValueFormatters\FormatterOptions)
#2 /var/www/html/extensions/Wikibase/lib/includes/Formatters/OutputFormatValueFormatterFactory.php(158): call_user_func(Closure, string, ValueFormatters\FormatterOptions)
#3 /var/www/html/extensions/Wikibase/lib/includes/Formatters/OutputFormatValueFormatterFactory.php(138): Wikibase\Lib\Formatters\OutputFormatValueFormatterFactory->buildDefinedFormatters(string, ValueFormatters\FormatterOptions)
#4 /var/www/html/extensions/Wikibase/lib/includes/Formatters/OutputFormatSnakFormatterFactory.php(108): Wikibase\Lib\Formatters\OutputFormatValueFormatterFactory->getValueFormatter(string, ValueFormatters\FormatterOptions)
#5 /var/www/html/extensions/Wikibase/repo/WikibaseRepo.ServiceWiring.php(1815): Wikibase\Lib\Formatters\OutputFormatSnakFormatterFactory->getSnakFormatter(string, ValueFormatters\FormatterOptions)
#6 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
#7 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#8 /var/www/html/includes/MediaWikiServices.php(279): Wikimedia\Services\ServiceContainer->getService(string)
#9 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(424): MediaWiki\MediaWikiServices->getService(string)
#10 /var/www/html/vendor/wikimedia/object-factory/src/ObjectFactory/ObjectFactory.php(209): Wikimedia\Services\ServiceContainer->get(string)
#11 /var/www/html/vendor/wikimedia/object-factory/src/ObjectFactory/ObjectFactory.php(150): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec(array, array)
#12 /var/www/html/includes/specialpage/SpecialPageFactory.php(1218): Wikimedia\ObjectFactory\ObjectFactory->createObject(array, array)
#13 /var/www/html/includes/specialpage/SpecialPageFactory.php(1253): MediaWiki\SpecialPage\SpecialPageFactory->getPage(string)
#14 /var/www/html/includes/specials/SpecialSpecialpages.php(53): MediaWiki\SpecialPage\SpecialPageFactory->getUsablePages(User)
#15 /var/www/html/includes/specials/SpecialSpecialpages.php(42): SpecialSpecialpages->getPageGroups()
#16 /var/www/html/includes/specialpage/SpecialPage.php(647): SpecialSpecialpages->execute(NULL)
#17 /var/www/html/includes/specialpage/SpecialPageFactory.php(1366): SpecialPage->run(NULL)
#18 /var/www/html/includes/MediaWiki.php(314): MediaWiki\SpecialPage\SpecialPageFactory->executePath(string, RequestContext)
#19 /var/www/html/includes/MediaWiki.php(932): MediaWiki->performRequest()
#20 /var/www/html/includes/MediaWiki.php(563): MediaWiki->main()
#21 /var/www/html/index.php(53): MediaWiki->run()
#22 /var/www/html/index.php(46): wfIndexMain()
#23 {main}
```

**Comment by JeroenDeDauw** [comment]
`dev-master` works fine. Looks like we did not do any release after adding 1.37 support. Lemme fix that.

**Comment by despens** [comment]
With the new release 1.0.2 the error is gone! 🙏
