### ISSUE TITLE
WikibaseRepo::getDefaultInstance() has been removed on master

### ISSUE THREAD

**Issue by toban** [ProfessionalWiki/WikibaseLocalMedia#8]
### Setup

- Wikibase Local Media version: head of master
- Wikibase version:  head of master
- MediaWiki version: head of master
- PHP version:  7.3

### Issue

WikibaseRepo::getDefaultInstance() has been removed as of https://gerrit.wikimedia.org/r/c/mediawiki/extensions/Wikibase/+/682951

visting Special:NewProperty with WikibaseLocalMedia results in
```
[3d56ca57adf3e1ae5900b952] /wiki/Special:NewProperty Error: Call to undefined method Wikibase\Repo\WikibaseRepo::getDefaultInstance()

Backtrace:

from /var/www/html/extensions/WikibaseLocalMedia/src/WikibaseLocalMedia.php(42)
#0 /var/www/html/extensions/WikibaseLocalMedia/src/HookHandlers.php(23): Wikibase\LocalMedia\WikibaseLocalMedia->getFormatterBuilder()
#1 [internal function]: Wikibase\LocalMedia\HookHandlers::Wikibase\LocalMedia\{closure}(string, ValueFormatters\FormatterOptions)
#2 /var/www/html/extensions/Wikibase/lib/includes/Formatters/OutputFormatValueFormatterFactory.php(158): call_user_func(Closure, string, ValueFormatters\FormatterOptions)
#3 /var/www/html/extensions/Wikibase/lib/includes/Formatters/OutputFormatValueFormatterFactory.php(138): Wikibase\Lib\Formatters\OutputFormatValueFormatterFactory->buildDefinedFormatters(string, ValueFormatters\FormatterOptions)
#4 /var/www/html/extensions/Wikibase/lib/includes/Formatters/OutputFormatSnakFormatterFactory.php(108): Wikibase\Lib\Formatters\OutputFormatValueFormatterFactory->getValueFormatter(string, ValueFormatters\FormatterOptions)
#5 /var/www/html/extensions/Wikibase/repo/WikibaseRepo.ServiceWiring.php(1637): Wikibase\Lib\Formatters\OutputFormatSnakFormatterFactory->getSnakFormatter(string, ValueFormatters\FormatterOptions)
#6 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(447): Wikimedia\Services\ServiceContainer->{closure}(MediaWiki\MediaWikiServices)
#7 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(416): Wikimedia\Services\ServiceContainer->createService(string)
#8 /var/www/html/includes/MediaWikiServices.php(266): Wikimedia\Services\ServiceContainer->getService(string)
#9 /var/www/html/vendor/wikimedia/services/src/ServiceContainer.php(424): MediaWiki\MediaWikiServices->getService(string)
#10 /var/www/html/vendor/wikimedia/object-factory/src/ObjectFactory/ObjectFactory.php(209): Wikimedia\Services\ServiceContainer->get(string)
#11 /var/www/html/vendor/wikimedia/object-factory/src/ObjectFactory/ObjectFactory.php(150): Wikimedia\ObjectFactory\ObjectFactory::getObjectFromSpec(array, array)
#12 /var/www/html/includes/specialpage/SpecialPageFactory.php(1222): Wikimedia\ObjectFactory\ObjectFactory->createObject(array, array)
#13 /var/www/html/includes/MediaWiki.php(272): MediaWiki\SpecialPage\SpecialPageFactory->getPage(string)
#14 /var/www/html/includes/MediaWiki.php(916): MediaWiki->performRequest()
#15 /var/www/html/includes/MediaWiki.php(550): MediaWiki->main()
#16 /var/www/html/index.php(53): MediaWiki->run()
#17 /var/www/html/index.php(46): wfIndexMain()
#18 {main}
```

**Comment by JeroenDeDauw** [comment]
Looks like this affects Wikibase 1.37 alpha and later, but no Wikibase 1.36

**Comment by toban** [comment]
good point!

**Comment by Universal-Omega** [comment]
@JeroenDeDauw Seeing has how 1.37 is now stable, can this please be resolved?

EDIT: Went ahead and did PR for this.
